# Generated by Django 6.0.8 on 2026-09-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0002_urgent_alerts"),
    ]

    operations = [
        migrations.AddField(
            model_name="urgentalert",
            name="email_failed_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="urgentalert",
            name="emailed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="urgentalert",
            name="emailed_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
