# Generated by Django 6.0.8 on 2026-09-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0003_alert_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="urgentalert",
            name="is_test",
            field=models.BooleanField(default=False),
        ),
    ]
