# Generated by Django 6.0.8 on 2026-10-08 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0017_ranking_min_share"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "max_students",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Blank for no limit (the biggest tier).",
                        null=True,
                    ),
                ),
                (
                    "monthly_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Blank until you set it: nobody on this tier is invoiced.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("currency", models.CharField(default="KES", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": [models.OrderBy(models.F("max_students"), nulls_last=True)],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=30, unique=True)),
                ("plan_name", models.CharField(max_length=60)),
                (
                    "students",
                    models.PositiveIntegerField(
                        help_text="Active students when it was issued."
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(max_length=3)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("issued_on", models.DateField()),
                ("due_on", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Unpaid"),
                            ("paid", "Paid"),
                            ("void", "Cancelled"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("paid_on", models.DateField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mpesa", "M-Pesa"),
                            ("bank", "Bank transfer"),
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("school_reported_at", models.DateTimeField(blank=True, null=True)),
                ("school_report", models.CharField(blank=True, max_length=500)),
                ("reminders_sent", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="students.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exempt",
                    models.BooleanField(
                        default=False,
                        help_text="Never invoiced or locked (demo, partner, or a founding school).",
                    ),
                ),
                (
                    "grace_days",
                    models.PositiveSmallIntegerField(
                        default=14,
                        help_text="Days after an invoice is due before the school is locked.",
                    ),
                ),
                (
                    "billing_email",
                    models.EmailField(
                        blank=True,
                        help_text="Also gets invoices and reminders (the school's admins always do).",
                        max_length=254,
                    ),
                ),
                (
                    "owner_notes",
                    models.TextField(
                        blank=True, help_text="For you only; the school never sees it."
                    ),
                ),
                ("locked_from", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="students.school",
                    ),
                ),
            ],
        ),
    ]
