# Generated by Django 6.0.8 on 2026-10-09 06:35
"""The owner's pricing: KES 50 a month for each active student. The size tiers are switched off (kept,
so turning one back on in the admin restores it)."""
from decimal import Decimal

from django.db import migrations, models

TIERS = ["Small", "Medium", "Large"]
PER_STUDENT = "Per student"


def forwards(apps, schema_editor):
    Plan = apps.get_model("billing", "Plan")
    Plan.objects.filter(name__in=TIERS).update(is_active=False)
    Plan.objects.get_or_create(name=PER_STUDENT, defaults={
        "max_students": None, "price_per_student": Decimal("50"), "currency": "KES", "is_active": True})


def backwards(apps, schema_editor):
    Plan = apps.get_model("billing", "Plan")
    Plan.objects.filter(name=PER_STUDENT).delete()
    Plan.objects.filter(name__in=TIERS).update(is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_tiers_and_existing_schools"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="price_per_student",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="A month, for each active student. Used when there's no flat price.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="monthly_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="A flat price a month. Blank: charged per student instead (below), or not at all.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
