# Generated by Django 6.0.7 on 2026-08-02 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_tone', models.CharField(choices=[('formal', 'Formal'), ('warm', 'Warm / encouraging'), ('concise', 'Concise / direct')], default='formal', help_text='School-level tone setting for AI-generated report comments (v1: per-school, not per-teacher).', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_groups', to='students.school')),
            ],
            options={
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('house', models.CharField(blank=True, max_length=100)),
                ('year_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='students.yeargroup')),
            ],
            options={
                'unique_together': {('year_group', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, help_text="Student ID as used in the school's own Excel sheet (Students.id column), for import matching.", max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('house', models.CharField(blank=True, max_length=100)),
                ('enrolled_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.school')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.schoolclass')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'external_id'], name='students_st_school__d65de7_idx')],
            },
        ),
    ]
