# Generated by Django 6.0.8 on 2026-09-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("female", "Female"), ("male", "Male"), ("other", "Other")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="medical_notes",
            field=models.TextField(
                blank=True,
                help_text="Allergies, conditions or medication staff should know about.",
                verbose_name="health notes",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="mode_of_learning",
            field=models.CharField(
                blank=True,
                choices=[("day", "Day"), ("boarding", "Boarding")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="nationality",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="photo_updated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="enrolled_on",
            field=models.DateField(
                blank=True, null=True, verbose_name="admission date"
            ),
        ),
    ]
