# Generated by Django 6.0.8 on 2026-09-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_profile_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="grading_scale",
            field=models.CharField(
                choices=[
                    ("cbc4", "CBC: 4 levels (EE, ME, AE, BE)"),
                    ("cbc8", "CBC junior school: 8 levels (EE1 to BE2)"),
                    ("percent", "Percentages only"),
                ],
                default="cbc4",
                help_text="Which performance levels to show next to percentages. See gradebook.levels.",
                max_length=10,
            ),
        ),
    ]
