# Generated by Django 6.0.8 on 2026-09-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_grading_scale"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="privacy_contact",
            field=models.CharField(
                blank=True,
                help_text="Who people contact about their personal data (Kenya Data Protection Act), e.g. an email address.",
                max_length=255,
            ),
        ),
    ]
