# Generated by Django 6.0.8 on 2026-09-27 09:34

from django.db import migrations, models
from django.utils import timezone


def existing_schools_are_set_up(apps, schema_editor):
    # Schools that were already using HouseMaster skip the new setup wizard.
    School = apps.get_model("students", "School")
    School.objects.filter(setup_completed_at__isnull=True).update(
        setup_completed_at=timezone.now(), education_system="cbc")


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_privacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="school",
            name="education_system",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cbc", "CBC"),
                    ("844", "8-4-4"),
                    ("british", "British / Cambridge"),
                    ("ib", "International Baccalaureate"),
                    ("american", "American"),
                ],
                help_text="Chosen in the setup wizard. See students.presets.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="school",
            name="motto",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="school",
            name="phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="school",
            name="setup_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="school",
            name="setup_progress",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="school",
            name="grading_scale",
            field=models.CharField(
                choices=[
                    ("cbc4", "CBC: 4 levels (EE, ME, AE, BE)"),
                    ("cbc8", "CBC junior/senior school: 8 levels (EE1 to BE2)"),
                    ("kcse", "KCSE letter grades (A to E)"),
                    ("igcse", "IGCSE letter grades (A* to G)"),
                    ("igcse9", "GCSE/IGCSE numbers (9 to 1)"),
                    ("ib", "IB grades (7 to 1)"),
                    ("american", "American letter grades (A to F)"),
                    ("percent", "Percentages only"),
                ],
                default="cbc4",
                help_text="Which performance levels to show next to percentages. See gradebook.levels.",
                max_length=10,
            ),
        ),
        migrations.RunPython(existing_schools_are_set_up, migrations.RunPython.noop),
    ]
