# Generated by Django 6.0.8 on 2026-09-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_school_setup"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="country",
            field=models.CharField(
                choices=[
                    ("ke", "Kenya"),
                    ("gb", "United Kingdom"),
                    ("us", "United States"),
                    ("other", "Another country"),
                ],
                default="ke",
                help_text="Decides the privacy law named in the privacy notice and local formats. See students.presets.",
                max_length=10,
            ),
        ),
    ]
