# Generated by Django 6.0.8 on 2026-09-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="pathway",
            field=models.CharField(
                blank=True,
                help_text="CBC senior school pathway, e.g. STEM. See students.presets.PATHWAYS.",
                max_length=60,
            ),
        ),
    ]
