# Generated by Django 6.0.8 on 2026-09-27 10:58

from django.db import migrations, models


def order_existing_year_groups(apps, schema_editor):
    # Year groups made before ordering existed keep the order they were created in.
    YearGroup = apps.get_model("students", "YearGroup")
    by_school = {}
    for yg in YearGroup.objects.order_by("id"):
        by_school.setdefault(yg.school_id, []).append(yg)
    for groups in by_school.values():
        for i, yg in enumerate(groups):
            yg.order = i
            yg.save(update_fields=["order"])


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_subject_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="vocab_overrides",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="student",
            name="graduated_on",
            field=models.DateField(
                blank=True,
                help_text="Set when they leave from a final year.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="yeargroup",
            name="is_final",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="yeargroup",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(order_existing_year_groups, migrations.RunPython.noop),
    ]
