# Generated by Django 6.0.8 on 2026-09-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0008_calendar"),
    ]

    operations = [
        migrations.AddField(
            model_name="yeargroup",
            name="education_system",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="yeargroup",
            name="grading_scale",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
