# Generated by Django 6.0.8 on 2026-09-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="checklist_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
