# Generated by Django 6.0.8 on 2026-09-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0010_checklist"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="structure_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
