# Generated by Django 6.0.8 on 2026-09-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0011_setup_stages"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="timezone",
            field=models.CharField(
                default="Africa/Nairobi",
                help_text='IANA time zone name, e.g. "Europe/London". Decides when the school\'s day starts ("today" for registers and dashboards). See students.localtime.',
                max_length=64,
            ),
        ),
    ]
