# Generated by Django 6.0.8 on 2026-10-01 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0012_school_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="support_attendance_min",
            field=models.PositiveSmallIntegerField(
                default=80,
                help_text="Suggest support when a student attends less than this percentage of days in the term.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="support_drop_points",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Suggest support when a student's average falls by at least this many points since last term.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="support_pass_mark",
            field=models.PositiveSmallIntegerField(
                default=40,
                help_text="Suggest support when a student's term average is below this percentage.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
