# Generated by Django 6.0.8 on 2026-10-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0013_school_support_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="has_boarding",
            field=models.BooleanField(default=False),
        ),
    ]
