# Generated by Django 6.0.8 on 2026-10-05 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0015_student_unique_admission_number_per_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="support_min_days",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Days of attendance recorded in a term before attendance can suggest support.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(200),
                ],
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="support_min_marks",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Marks a student needs in a term before their average can suggest support.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(50),
                ],
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="support_reopen_points",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="A dismissed suggestion comes back that term if the average or attendance falls this many more points.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="yeargroup",
            name="support_pass_mark",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
