# Generated by Django 6.0.8 on 2026-10-05 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0016_support_thresholds"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="ranking_min_share",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Percent of the usual subjects a student needs marks in to be ranked.",
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
    ]
