# Generated by Django 6.0.8 on 2026-10-05 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0013_unique_email"),
        ("students", "0013_school_support_limits"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardingHouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boarding_houses",
                        to="students.school",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="boarding_houses",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Dorm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dorms",
                        to="boarding.boardinghouse",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "student",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bed",
                        to="students.student",
                    ),
                ),
                (
                    "dorm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beds",
                        to="boarding.dorm",
                    ),
                ),
            ],
            options={
                "ordering": ["dorm__name", "id"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("weekend", "Weekend"),
                            ("half_term", "Half term"),
                            ("exeat", "Exeat"),
                            ("appointment", "Appointment"),
                            ("other", "Other"),
                        ],
                        default="weekend",
                        max_length=12,
                    ),
                ),
                ("leaving_at", models.DateTimeField()),
                ("returning_at", models.DateTimeField()),
                ("reason", models.TextField(blank=True)),
                (
                    "collected_by",
                    models.CharField(
                        blank=True,
                        help_text="Who collects the boarder.",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Waiting for a decision"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                            ("out", "Signed out"),
                            ("returned", "Back"),
                        ],
                        default="requested",
                        max_length=10,
                    ),
                ),
                ("requested_by_name", models.CharField(blank=True, max_length=200)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("decided_by_name", models.CharField(blank=True, max_length=200)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("signed_out_at", models.DateTimeField(blank=True, null=True)),
                ("signed_out_by_name", models.CharField(blank=True, max_length=200)),
                ("signed_in_at", models.DateTimeField(blank=True, null=True)),
                ("signed_in_by_name", models.CharField(blank=True, max_length=200)),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="students.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-leaving_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RollCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "session",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("evening", "Evening"),
                            ("night", "Night"),
                        ],
                        max_length=10,
                    ),
                ),
                ("taken_by_name", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roll_calls",
                        to="boarding.boardinghouse",
                    ),
                ),
                (
                    "taken_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RollCallEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("present", "Present"),
                            ("missing", "Missing"),
                            ("on_leave", "On leave"),
                            ("sick_bay", "In sick bay"),
                        ],
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "roll_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="boarding.rollcall",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roll_call_entries",
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SickBayVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checked_in_at", models.DateTimeField()),
                ("checked_in_by_name", models.CharField(blank=True, max_length=200)),
                (
                    "complaint",
                    models.TextField(help_text="Why they came, e.g. headache, fever."),
                ),
                (
                    "treatment",
                    models.TextField(blank=True, help_text="What was given or done."),
                ),
                ("checked_out_at", models.DateTimeField(blank=True, null=True)),
                ("checked_out_by_name", models.CharField(blank=True, max_length=200)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("back", "Back to lessons or the house"),
                            ("home", "Sent home"),
                            ("hospital", "Sent to hospital or a clinic"),
                        ],
                        max_length=10,
                    ),
                ),
                ("parents_told_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parents_told_how",
                    models.CharField(
                        blank=True,
                        help_text="e.g. phoned mother, emailed.",
                        max_length=200,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sick_bay_visits",
                        to="students.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sick_bay_visits",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_in_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="boardinghouse",
            constraint=models.UniqueConstraint(
                fields=("school", "name"), name="unique_boarding_house_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="dorm",
            constraint=models.UniqueConstraint(
                fields=("house", "name"), name="unique_dorm_name_per_house"
            ),
        ),
        migrations.AddConstraint(
            model_name="rollcall",
            constraint=models.UniqueConstraint(
                fields=("house", "date", "session"), name="one_roll_call_per_session"
            ),
        ),
        migrations.AddConstraint(
            model_name="rollcallentry",
            constraint=models.UniqueConstraint(
                fields=("roll_call", "student"), name="one_entry_per_boarder"
            ),
        ),
    ]
