# Generated by Django 6.0.8 on 2026-10-05 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boarding", "0001_initial"),
        ("students", "0014_school_has_boarding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Absence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved")],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("found", "Found"),
                            ("returned", "Returned"),
                            ("on_leave", "On authorised leave"),
                            ("left_school", "Left the school"),
                            ("no_longer_boarding", "No longer boarding"),
                            ("recorded_in_error", "Marked missing by mistake"),
                        ],
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by_name", models.CharField(blank=True, max_length=200)),
                ("resolution_note", models.CharField(blank=True, max_length=500)),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="absences",
                        to="boarding.boardinghouse",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "roll_call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="absences",
                        to="boarding.rollcall",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["opened_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "open")),
                        fields=("student",),
                        name="one_open_absence_per_boarder",
                    )
                ],
            },
        ),
    ]
