# Generated by Django 6.0.8 on 2026-10-05 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boarding", "0002_absence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RollCallAmendment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amended_by_name", models.CharField(blank=True, max_length=200)),
                ("amended_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.CharField(max_length=300)),
                ("changes", models.JSONField(default=list)),
                (
                    "amended_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "roll_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amendments",
                        to="boarding.rollcall",
                    ),
                ),
            ],
            options={
                "ordering": ["amended_at", "id"],
            },
        ),
    ]
