# Generated by Django 6.0.8 on 2026-10-05 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boarding", "0003_rollcallamendment"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardinghouse",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="rollcall",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="roll_calls",
                to="boarding.boardinghouse",
            ),
        ),
    ]
