# Generated by Django 6.0.8 on 2026-10-06 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boarding", "0004_house_archive_protect_history"),
        ("students", "0014_school_has_boarding"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoarderRestriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leave_admin_only", models.BooleanField(default=False)),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="For boarding staff; never shown to parents.",
                        max_length=300,
                    ),
                ),
                ("set_by_name", models.CharField(blank=True, max_length=200)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boarding_restriction",
                        to="students.student",
                    ),
                ),
            ],
        ),
    ]
