# Generated by Django 6.0.8 on 2026-10-07 08:09

import django.db.models.deletion
from django.db import migrations, models


def from_beds(apps, schema_editor):
    """Every current boarder in a bed belongs to that bed's house."""
    Bed = apps.get_model("boarding", "Bed")
    HouseAllocation = apps.get_model("boarding", "HouseAllocation")
    rows = [HouseAllocation(student_id=b.student_id, house_id=b.dorm.house_id, allocated_by_name="From their bed")
            for b in Bed.objects.filter(student__isnull=False, student__is_active=True,
                                        student__mode_of_learning="boarding").select_related("dorm")]
    HouseAllocation.objects.bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("boarding", "0005_boarder_restriction"),
        ("students", "0017_ranking_min_share"),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allocated_by_name", models.CharField(blank=True, max_length=200)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="boarding.boardinghouse",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="house_allocation",
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.RunPython(from_beds, migrations.RunPython.noop),
    ]
