# Generated by Django 6.0.8 on 2026-10-08 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0017_ranking_min_share"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_feed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("holiday", "Holiday or school closed"),
                            ("exam", "Exams"),
                            ("meeting", "Parents' meeting"),
                            ("trip", "Trip or visit"),
                            ("sport", "Sport"),
                            ("performance", "Performance or show"),
                            ("deadline", "Deadline"),
                            ("event", "Event"),
                            ("staff", "Staff training or meeting"),
                        ],
                        default="event",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=150)),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Blank for a one-day event.", null=True
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, help_text="Blank for all day.", null=True
                    ),
                ),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "staff_only",
                    models.BooleanField(
                        default=False, help_text="Parents and students don't see it."
                    ),
                ),
                ("created_by_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="students.school",
                    ),
                ),
                (
                    "year_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Blank for the whole school.",
                        related_name="calendar_events",
                        to="students.yeargroup",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date", "start_time", "id"],
                "indexes": [
                    models.Index(
                        fields=["school", "start_date"],
                        name="schoolcalen_school__dcfe39_idx",
                    )
                ],
            },
        ),
    ]
