"""
Django settings for housemaster project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import os
import sys

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Local development reads a .env file. Tests of the settings themselves set
# HOUSEMASTER_SKIP_DOTENV=1 so a developer's .env can't leak into them.
if os.environ.get('HOUSEMASTER_SKIP_DOTENV') != '1':
    load_dotenv(BASE_DIR / '.env')

# True while `manage.py test` is running.
TESTING = sys.argv[1:2] == ['test']


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Off unless DJANGO_DEBUG=True is set explicitly. Local development sets it
# in .env (see .env.example). With DEBUG off the settings below refuse to
# start on a missing or unsafe value instead of quietly using a default.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'


def _production_setting_error(name, problem):
    return ImproperlyConfigured(
        f"{name} {problem}. Set it in the environment (see docs/ENVIRONMENT.md). "
        "For local development put DJANGO_DEBUG=True in .env instead."
    )


# SECURITY WARNING: keep the secret key used in production secret!
# It signs every login token, so production must supply its own. The
# development key below is only ever used with DEBUG on.
SECRET_KEY = os.environ.get('SECRET_KEY', '')
if DEBUG and not SECRET_KEY:
    SECRET_KEY = 'django-insecure-local-development-only-never-use-this-in-production'
if not DEBUG:
    if not SECRET_KEY:
        raise _production_setting_error('SECRET_KEY', 'is not set')
    if len(SECRET_KEY) < 50 or SECRET_KEY.startswith('django-insecure'):
        raise _production_setting_error(
            'SECRET_KEY', "must be at least 50 random characters and must not start with 'django-insecure'"
        )

# Comma-separated list of allowed hostnames in production, e.g.
# "housemaster-api.onrender.com". Local dev values always included.
_env_allowed_hosts = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
    if host.strip()
]
if not DEBUG and not _env_allowed_hosts:
    raise _production_setting_error('DJANGO_ALLOWED_HOSTS', 'is empty')
ALLOWED_HOSTS = ["localhost", "127.0.0.1", "testserver"] + _env_allowed_hosts


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    # Rotated and signed-out refresh tokens are remembered here so they
    # can't be used again.
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'corsheaders',
    'accounts',
    'students',
    'gradebook',
    'attendance',
    'reporting',
    'communications',
    'guardians',
    'messaging',
    'activity',
    'approvals',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves static files (Django admin CSS, DRF browsable-API
    # assets) directly from the Django process, right after
    # SecurityMiddleware per WhiteNoise's own placement requirement — no
    # separate static file host needed on Render.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# The Django admin's address. Production should use something hard to
# guess (docs/ENVIRONMENT.md); the default suits local development.
ADMIN_PATH = os.environ.get('DJANGO_ADMIN_PATH', 'admin/').strip().strip('/') + '/'
# Failed sign-ins allowed on the admin login page per client address per
# hour (housemaster/middleware.py).
ADMIN_LOGIN_RATE = int(os.environ.get('ADMIN_LOGIN_RATE', '10'))
MIDDLEWARE.insert(MIDDLEWARE.index('django.contrib.sessions.middleware.SessionMiddleware'),
                  'housemaster.middleware.AdminLoginThrottleMiddleware')

# Temporary diagnostic for finding Render's proxy count (housemaster/middleware.py).
if os.environ.get('LOG_CLIENT_IP_DEBUG') == '1':
    MIDDLEWARE.insert(0, 'housemaster.middleware.ClientIPDebugMiddleware')
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {'console': {'class': 'logging.StreamHandler'}},
        'loggers': {'housemaster.client_ip': {'handlers': ['console'], 'level': 'INFO'}},
    }

_num_proxies = os.environ.get('DRF_NUM_PROXIES', '').strip()
DRF_NUM_PROXIES = int(_num_proxies) if _num_proxies else None

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # simplejwt's JWT authentication, refusing tokens issued before a
        # password change or deactivation (accounts/tokens.py).
        'accounts.authentication.VersionedJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        # Filters on linked records never reveal whether an ID exists at
        # another school. See accounts/filters.py.
        'accounts.filters.SchoolSafeFilterBackend',
    ],
    # JSON only. DRF's HTML "browsable API" builds its forms from whole
    # database tables, which would list other schools' records, and the
    # app never uses it.
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    # ScopedRateThrottle is a no-op for any view that doesn't set
    # `throttle_scope` (see DRF internals), so enabling it globally here is
    # safe — it only actually throttles the two Gemini-backed endpoints
    # that explicitly opt in (StudentReportViewSet.generate,
    # AnnouncementViewSet.generate_text), not every endpoint in the app.
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # Per-user, per-hour caps on the two AI-generation endpoints —
        # generous for real usage (a teacher generating reports for a
        # whole class in one sitting) while stopping a runaway
        # script/loop from running up a real Gemini bill. Overridable via
        # env var without a redeploy-worthy code change if these turn out
        # to be too tight or too loose in practice.
        'ai_report_generation': os.environ.get('AI_REPORT_GENERATION_RATE', '30/hour'),
        # Starting AI reports for a whole class counts once here, not per report.
        'ai_class_report_generation': os.environ.get('AI_CLASS_REPORT_GENERATION_RATE', '5/hour'),
        'ai_announcement_drafting': os.environ.get('AI_ANNOUNCEMENT_DRAFTING_RATE', '30/hour'),
        # New school sign-ups per IP address, and per email address.
        'school_registration': os.environ.get('SCHOOL_REGISTRATION_RATE', '5/hour'),
        'school_registration_email': os.environ.get('SCHOOL_REGISTRATION_EMAIL_RATE', '3/day'),
        # Brute-force and mail-bombing limits on the public endpoints
        # (accounts/throttles.py). Each is per IP address, and where the
        # request names an account, per email address too. Only failed
        # logins count. Schools and mobile networks put many people behind
        # one address, so the per-IP limits are deliberately generous.
        'login_ip': os.environ.get('LOGIN_IP_RATE', '30/hour'),
        'login_email': os.environ.get('LOGIN_EMAIL_RATE', '10/hour'),
        'password_reset_ip': os.environ.get('PASSWORD_RESET_IP_RATE', '20/hour'),
        'password_reset_email': os.environ.get('PASSWORD_RESET_EMAIL_RATE', '5/hour'),
        # Invite previews and acceptance, parent invites, class sign-up
        # links and password-reset confirmation (token-guessing endpoints).
        'invite_ip': os.environ.get('INVITE_IP_RATE', '60/hour'),
        'token_refresh_ip': os.environ.get('TOKEN_REFRESH_IP_RATE', '600/hour'),
        # Invite emails (new or renewed): per admin, and per recipient address
        # across all schools, so invites can't flood someone's inbox.
        'invite_send_user': os.environ.get('INVITE_SEND_USER_RATE', '100/hour'),
        'invite_send_recipient': os.environ.get('INVITE_SEND_RECIPIENT_RATE', '5/day'),
    },
    # How many proxies sit in front of the app and append to
    # X-Forwarded-For. Without it DRF trusts the whole header, so anyone can
    # pick their own "IP address" and dodge the per-IP limits. Production
    # must set DRF_NUM_PROXIES (docs/ENVIRONMENT.md explains how to find the
    # right value with LOG_CLIENT_IP_DEBUG).
    'NUM_PROXIES': DRF_NUM_PROXIES,
}

ROOT_URLCONF = 'housemaster.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'housemaster.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Reads DATABASE_URL from the environment (see .env / .env.example). Local
# development without one uses SQLite; production must set it, so a missing
# value can never quietly start the app on an empty SQLite file.
if not DEBUG and not os.environ.get('DATABASE_URL'):
    raise _production_setting_error('DATABASE_URL', 'is not set')

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        ssl_require=False,  # the Neon URL itself carries ?sslmode=require
    )
}

# The test runner creates and destroys a whole database. It must never do
# that on a shared server, so it only runs on SQLite or a local Postgres
# unless ALLOW_REMOTE_TEST_DB=1 is set on purpose.
if TESTING and os.environ.get('ALLOW_REMOTE_TEST_DB') != '1':
    _test_db_host = DATABASES['default'].get('HOST') or ''
    if _test_db_host not in ('', 'localhost', '127.0.0.1', '::1'):
        raise ImproperlyConfigured(
            "Refusing to run the tests against a remote database. Unset DATABASE_URL "
            "(env -u DATABASE_URL ...) or move .env aside, or set ALLOW_REMOTE_TEST_DB=1 "
            "if this really is a disposable test server."
        )


# Cache. The rate limits keep their counters here. The default in-memory
# cache is per process and is emptied on every restart (which the free tier
# does whenever it sleeps), so production should set THROTTLE_CACHE=db and
# run `manage.py createcachetable` in the build (docs/HUMAN_ACTIONS.md, H-5).
if os.environ.get('THROTTLE_CACHE', '').strip().lower() == 'db':
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
            'LOCATION': 'housemaster_cache',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# Staff log in by email, not username — see accounts.auth_backends.EmailBackend
# for details. ModelBackend stays listed so /admin/'s username-based login
# form (which Django's admin hardcodes) keeps working unchanged.
AUTHENTICATION_BACKENDS = [
    "accounts.auth_backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# The schools are in Kenya. Times are stored in UTC (USE_TZ), and "today"
# (timezone.localdate()) is Nairobi's day, so registers taken just after
# midnight land on the right date.
TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Where `collectstatic` gathers files to on Render's build step; WhiteNoise
# serves from here at runtime. Doesn't exist/matter for local dev (no one
# runs collectstatic there), so it's safe to leave set unconditionally.
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# CORS: allow the frontend's origin(s) to call this API.
# In dev, Vite can bump to a different port (5174, 5175...) if 5173 is
# taken, so we allow any localhost/127.0.0.1 port via regex — avoids this
# breaking every time a stray process is already holding port 5173.
# Gated to DEBUG only: production must not accept a request just because
# its Origin header claims to be some localhost port.
if DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r'^http://localhost:\d+$',
        r'^http://127\.0\.0\.1:\d+$',
    ]

# Exact-origin allowlist — this is what actually matters in production.
# Let the frontend read the file name of downloads (exports, the import
# template); browsers hide this header from other origins otherwise.
CORS_EXPOSE_HEADERS = ["Content-Disposition"]

# Set CORS_ALLOWED_ORIGINS in Render to the real Vercel URL(s), e.g.
# "https://housemaster.vercel.app,https://housemaster-git-main-yourteam.vercel.app"
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
    if origin.strip()
]
if not DEBUG:
    if not CORS_ALLOWED_ORIGINS:
        raise _production_setting_error('CORS_ALLOWED_ORIGINS', 'is empty')
    if any('*' in o or 'localhost' in o or '127.0.0.1' in o for o in CORS_ALLOWED_ORIGINS):
        raise _production_setting_error(
            'CORS_ALLOWED_ORIGINS', "must list the real frontend origins only (no '*', localhost or 127.0.0.1)"
        )


from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.environ.get('JWT_ACCESS_TOKEN_MINUTES', '60'))),
    # Every refresh hands out a new refresh token and retires the old one,
    # so someone who keeps using the app stays signed in while a stolen
    # refresh token stops working after a few days at most.
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.environ.get('JWT_REFRESH_TOKEN_DAYS', '3'))),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'TOKEN_REFRESH_SERIALIZER': 'accounts.tokens.VersionedTokenRefreshSerializer',
    # Record each login on User.last_login, shown on the admin's staff and
    # parent lists.
    'UPDATE_LAST_LOGIN': True,
}

# Staff invite emails (accounts.Invite).
# In dev, EMAIL_BACKEND defaults to the console backend, so invite emails
# just print to the runserver log instead of actually sending — set
# EMAIL_BACKEND/EMAIL_HOST/etc. via the environment for real SMTP delivery
# in production. FRONTEND_URL is the base URL the accept-invite link points
# at (the deployed Vercel URL in production, the local Vite dev server for
# now).
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend'
)
# In production the console backend would write invite and reset links into
# the server log. Drop such mail with an ERROR instead; `check --deploy`
# still reports the missing email setup (housemaster.E002).
if not DEBUG and EMAIL_BACKEND == 'django.core.mail.backends.console.EmailBackend':
    EMAIL_BACKEND = 'housemaster.mail.UndeliveredEmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'true').lower() == 'true'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@housemaster.local')

FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# Production-only hardening. Skipped when DEBUG=True so local dev over
# plain http://127.0.0.1:8001 still works without a redirect loop.
if not DEBUG:
    # Render terminates TLS in front of the app and forwards over HTTP,
    # setting X-Forwarded-Proto — this tells Django to trust that header
    # when deciding request.is_secure(), which SECURE_SSL_REDIRECT below
    # depends on.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # 30 days. Raise to a year (31536000) after a clean month. No preload:
    # that is hard to undo.
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', str(60 * 60 * 24 * 30)))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# Error monitoring (Sentry). Only initializes if SENTRY_DSN is set in the
# environment, so local dev (and CI) with no DSN configured is unaffected —
# nothing breaks, errors just aren't reported anywhere. Set SENTRY_DSN on
# Render to start getting real production error reports.
SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        # Fraction of requests to trace for performance monitoring. Kept
        # low since this is a small app on a free-tier host — raise if
        # request-level timing data becomes useful later.
        traces_sample_rate=0.2,
        # Sentry's own default; scrubs cookies, auth headers, and
        # request bodies from error reports so JWT tokens and passwords
        # submitted in login/report-generation requests are never sent
        # to Sentry.
        send_default_pii=False,
        environment=os.environ.get('SENTRY_ENVIRONMENT', 'production' if not DEBUG else 'development'),
    )

# Years after a student leaves (their graduated_on date) before
# `manage.py apply_retention --apply` anonymises them. Unset means off:
# the period is for counsel to decide (docs/DESIGN_data_subject_tooling.md).
_retention_years = os.environ.get('RETENTION_INACTIVE_STUDENT_YEARS', '').strip()
RETENTION_INACTIVE_STUDENT_YEARS = int(_retention_years) if _retention_years else None

# Parent notification emails are sent on a background thread so publishing to
# a whole school doesn't hold up the request. Tests send them inline.
NOTIFICATIONS_IN_BACKGROUND = os.environ.get('NOTIFICATIONS_IN_BACKGROUND', 'true').lower() == 'true' \
    and 'test' not in sys.argv[1:2]
