"""
Django settings for housemaster project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import os

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Reads SECRET_KEY from the environment in production (set this in Render's
# dashboard); falls back to the old insecure dev key so local dev with no
# .env still works out of the box, same pattern as DATABASE_URL below.
SECRET_KEY = os.environ.get(
    'SECRET_KEY', 'django-insecure-y9g=yf*er$t!1v1kye1bc523&6b_1(*by6&%v^nlrj232-bu0^'
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True (local dev), so this is opt-out, not opt-in — Render
# MUST set DJANGO_DEBUG=False explicitly, or the deployment is still
# running with DEBUG=True.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Comma-separated list of allowed hostnames in production, e.g.
# "housemaster-api.onrender.com". Local dev values always included.
ALLOWED_HOSTS = ["localhost", "127.0.0.1", "testserver"] + [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'corsheaders',
    'accounts',
    'students',
    'gradebook',
    'attendance',
    'reporting',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves static files (Django admin CSS, DRF browsable-API
    # assets) directly from the Django process, right after
    # SecurityMiddleware per WhiteNoise's own placement requirement — no
    # separate static file host needed on Render.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}

ROOT_URLCONF = 'housemaster.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'housemaster.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Reads DATABASE_URL from the environment (see .env / .env.example).
# Falls back to local SQLite if DATABASE_URL isn't set, so this still works
# out of the box for anyone who hasn't configured Postgres yet.

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        ssl_require=False,  # the Neon URL itself carries ?sslmode=require
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Where `collectstatic` gathers files to on Render's build step; WhiteNoise
# serves from here at runtime. Doesn't exist/matter for local dev (no one
# runs collectstatic there), so it's safe to leave set unconditionally.
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# CORS: allow the frontend's origin(s) to call this API.
# In dev, Vite can bump to a different port (5174, 5175...) if 5173 is
# taken, so we allow any localhost/127.0.0.1 port via regex — avoids this
# breaking every time a stray process is already holding port 5173.
# Gated to DEBUG only: production must not accept a request just because
# its Origin header claims to be some localhost port.
if DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r'^http://localhost:\d+$',
        r'^http://127\.0\.0\.1:\d+$',
    ]

# Exact-origin allowlist — this is what actually matters in production.
# Set CORS_ALLOWED_ORIGINS in Render to the real Vercel URL(s), e.g.
# "https://housemaster.vercel.app,https://housemaster-git-main-yourteam.vercel.app"
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
    if origin.strip()
]


from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# Staff invite emails (accounts.Invite).
# In dev, EMAIL_BACKEND defaults to the console backend, so invite emails
# just print to the runserver log instead of actually sending — set
# EMAIL_BACKEND/EMAIL_HOST/etc. via the environment for real SMTP delivery
# in production. FRONTEND_URL is the base URL the accept-invite link points
# at (the deployed Vercel URL in production, the local Vite dev server for
# now).
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'true').lower() == 'true'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@housemaster.local')

FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# Production-only hardening. Skipped when DEBUG=True so local dev over
# plain http://127.0.0.1:8001 still works without a redirect loop.
if not DEBUG:
    # Render terminates TLS in front of the app and forwards over HTTP,
    # setting X-Forwarded-Proto — this tells Django to trust that header
    # when deciding request.is_secure(), which SECURE_SSL_REDIRECT below
    # depends on.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 7  # start at 1 week, raise once confirmed working
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# Error monitoring (Sentry). Only initializes if SENTRY_DSN is set in the
# environment, so local dev (and CI) with no DSN configured is unaffected —
# nothing breaks, errors just aren't reported anywhere. Set SENTRY_DSN on
# Render to start getting real production error reports.
SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        # Fraction of requests to trace for performance monitoring. Kept
        # low since this is a small app on a free-tier host — raise if
        # request-level timing data becomes useful later.
        traces_sample_rate=0.2,
        # Sentry's own default; scrubs cookies, auth headers, and
        # request bodies from error reports so JWT tokens and passwords
        # submitted in login/report-generation requests are never sent
        # to Sentry.
        send_default_pii=False,
        environment=os.environ.get('SENTRY_ENVIRONMENT', 'production' if not DEBUG else 'development'),
    )