# Generated by Django 6.0.8 on 2026-10-09 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gradebook", "0007_grade_ranges"),
        ("students", "0017_ranking_min_share"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("all", "Everyone"),
                            ("boarding", "Boarders only"),
                            ("day", "Day students only"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_items",
                        to="students.school",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_items",
                        to="gradebook.term",
                    ),
                ),
                (
                    "year_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Blank for every year group.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_items",
                        to="students.yeargroup",
                    ),
                ),
            ],
            options={
                "ordering": ["term_id", "year_group_id", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="FeeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(default="KES", max_length=3)),
                (
                    "payment_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Shown to parents, e.g. the paybill and account.",
                    ),
                ),
                ("next_receipt", models.PositiveIntegerField(default=1)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_settings",
                        to="students.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("paid_on", models.DateField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("mpesa", "M-Pesa"),
                            ("bank", "Bank transfer"),
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("card", "Card"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("payer_name", models.CharField(blank=True, max_length=150)),
                ("receipt_number", models.CharField(max_length=30)),
                ("recorded_by_name", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.CharField(blank=True, max_length=200)),
                ("voided_by_name", models.CharField(blank=True, max_length=150)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_payments",
                        to="students.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_payments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["paid_on", "id"],
            },
        ),
        migrations.CreateModel(
            name="PaymentClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claimed_by_name", models.CharField(max_length=150)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("paid_on", models.DateField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("mpesa", "M-Pesa"),
                            ("bank", "Bank transfer"),
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("card", "Card"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("reference", models.CharField(max_length=100)),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Waiting to be checked"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Not found"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("decided_by_name", models.CharField(blank=True, max_length=150)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("reject_reason", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claimed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claim",
                        to="fees.payment",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_claims",
                        to="students.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_claims",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Charge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("fee", "Fee"),
                            ("extra", "Extra charge"),
                            ("discount", "Discount or bursary"),
                        ],
                        default="fee",
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(max_length=150)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_by_name", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_charges",
                        to="students.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_charges",
                        to="students.student",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fee_charges",
                        to="gradebook.term",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="charges",
                        to="fees.feeitem",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("item__isnull", False)),
                        fields=("student", "item"),
                        name="one_charge_per_fee_item",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("school", "receipt_number"), name="one_receipt_number"
            ),
        ),
    ]
