# Generated by Django 6.0.8 on 2026-10-09 19:54

import django.db.models.deletion
import mpesa.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0003_per_student_price"),
        ("fees", "0001_initial"),
        ("students", "0017_ranking_min_share"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="C2BPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("fees", "School fees"),
                            ("subscription", "HouseMaster subscription"),
                        ],
                        max_length=15,
                    ),
                ),
                ("trans_id", models.CharField(max_length=30, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("bill_ref", models.CharField(blank=True, max_length=60)),
                ("payer_name", models.CharField(blank=True, max_length=150)),
                ("phone_masked", models.CharField(blank=True, max_length=20)),
                ("paid_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recorded", "Recorded"),
                            ("unmatched", "Needs a student"),
                            ("ignored", "Not for fees"),
                        ],
                        max_length=10,
                    ),
                ),
                ("handled_by_name", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fee_payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="c2b_payment",
                        to="fees.payment",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="c2b_payments",
                        to="billing.invoice",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="c2b_payments",
                        to="students.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="c2b_payments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MpesaAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("paybill", "Paybill"), ("till", "Till (Buy Goods)")],
                        default="paybill",
                        max_length=10,
                    ),
                ),
                ("shortcode", models.CharField(max_length=10)),
                ("till_number", models.CharField(blank=True, max_length=10)),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("sandbox", "Sandbox (testing)"),
                            ("production", "Live"),
                        ],
                        default="sandbox",
                        max_length=10,
                    ),
                ),
                ("consumer_key", models.TextField(blank=True)),
                ("consumer_secret", models.TextField(blank=True)),
                ("passkey", models.TextField(blank=True)),
                (
                    "callback_token",
                    models.CharField(
                        default=mpesa.models.new_token, max_length=64, unique=True
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("c2b_registered_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mpesa_account",
                        to="students.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StkRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("fees", "School fees"),
                            ("subscription", "HouseMaster subscription"),
                        ],
                        max_length=15,
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                ("phone_masked", models.CharField(max_length=20)),
                ("account_reference", models.CharField(max_length=20)),
                ("merchant_request_id", models.CharField(blank=True, max_length=100)),
                ("checkout_request_id", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for the payer"),
                            ("paid", "Paid"),
                            ("failed", "Not paid"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("result_description", models.CharField(blank=True, max_length=255)),
                ("receipt", models.CharField(blank=True, max_length=30)),
                ("requested_by_name", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fee_payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stk_request",
                        to="fees.payment",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stk_requests",
                        to="billing.invoice",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stk_requests",
                        to="students.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stk_requests",
                        to="students.student",
                    ),
                ),
            ],
        ),
    ]
