# Generated by Django 6.0.8 on 2026-10-05 12:16

import admissions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0014_school_has_boarding"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionsSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_open", models.BooleanField(default=False)),
                (
                    "token",
                    models.CharField(
                        default=admissions.models._token, max_length=40, unique=True
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="Shown at the top of the application form.",
                    ),
                ),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admissions_settings",
                        to="students.school",
                    ),
                ),
                (
                    "year_groups",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="students.yeargroup"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewing", "Reviewing"),
                            ("interview", "Interview or test"),
                            ("offered", "Offered a place"),
                            ("accepted", "Place accepted"),
                            ("waitlist", "Waiting list"),
                            ("declined", "Not offered a place"),
                            ("withdrawn", "Withdrawn"),
                            ("enrolled", "Enrolled"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
                (
                    "start",
                    models.CharField(
                        blank=True,
                        help_text="When they'd like to start, e.g. January 2027.",
                        max_length=100,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=10)),
                ("nationality", models.CharField(blank=True, max_length=60)),
                ("current_school", models.CharField(blank=True, max_length=200)),
                ("mode_of_learning", models.CharField(blank=True, max_length=10)),
                ("medical_notes", models.TextField(blank=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Anything else the family wants the school to know.",
                    ),
                ),
                ("parent_name", models.CharField(max_length=200)),
                ("parent_email", models.EmailField(max_length=254)),
                ("parent_phone", models.CharField(blank=True, max_length=40)),
                ("relationship", models.CharField(blank=True, max_length=20)),
                ("staff_notes", models.TextField(blank=True, help_text="Staff only.")),
                ("interview_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision_note",
                    models.TextField(
                        blank=True, help_text="Sent to the family with the decision."
                    ),
                ),
                ("decided_by_name", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="students.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="students.student",
                    ),
                ),
                (
                    "year_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="students.yeargroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
