# Generated by Django 6.0.8 on 2026-10-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="confirm_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="confirm_token",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="application",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
