# Generated by Django 6.0.8 on 2026-10-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0002_confirm_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="admissionssettings",
            name="retention_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
