# Generated by Django 6.0.8 on 2026-10-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0003_retention_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="admissionssettings",
            name="next_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="admissionssettings",
            name="number_prefix",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
