# Generated by Django 6.0.8 on 2026-10-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0004_admission_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="has_needs",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
