# Generated by Django 6.0.8 on 2026-09-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='name',
            field=models.CharField(blank=True, help_text="Full name of the invitee — for the admin's own reference.", max_length=255),
        ),
    ]
