# Generated by Django 6.0.7 on 2026-09-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.EmailField(help_text='The email this staff member will use to sign in.', max_length=254),
        ),
    ]
