# Generated by Django 6.0.7 on 2026-09-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_invite_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, help_text="The staff member's name shown throughout HouseMaster. Never use their login email as a display name.", max_length=255),
        ),
    ]
