# Generated by Django 6.0.8 on 2026-09-26 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_teachingassignment"),
        ("gradebook", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teachingassignment",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave empty for every subject in the class.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="gradebook.subject",
            ),
        ),
    ]
