# Generated by Django 6.0.8 on 2026-09-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_privacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="invite",
            name="assignments",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Classes to assign when the invite is accepted: [{"school_class": id, "subject": id or null}].',
            ),
        ),
    ]
