# Generated by Django 6.0.8 on 2026-09-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_invite_assignments"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="checklist_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="tour_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
