# Generated by Django 6.0.8 on 2026-10-08 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_unique_email"),
        ("gradebook", "0007_grade_ranges"),
        ("students", "0017_ranking_min_share"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("teacher", "Teacher"),
                    ("governor", "Governor"),
                ],
                default="teacher",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("teacher", "Teacher"),
                    ("governor", "Governor"),
                ],
                default="teacher",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="StaffRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("leadership", "Leadership"),
                            ("head_of_year", "Head of Year"),
                            ("head_of_department", "Head of Department"),
                            ("class_teacher", "Class Teacher"),
                            ("nurse", "Nurse"),
                            ("admissions", "Admissions Officer"),
                            ("secretary", "Secretary"),
                        ],
                        max_length=30,
                    ),
                ),
                ("assigned_by_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_roles",
                        to="accounts.profile",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_roles",
                        to="students.schoolclass",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_roles",
                        to="gradebook.subject",
                    ),
                ),
                (
                    "year_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_roles",
                        to="students.yeargroup",
                    ),
                ),
            ],
            options={
                "ordering": ["role", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "profile",
                            "role",
                            "year_group",
                            "subject",
                            "school_class",
                        ),
                        name="unique_staff_role",
                    )
                ],
            },
        ),
    ]
