# Generated by Django 6.0.8 on 2026-10-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_staff_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("leadership", "Leadership"),
                    ("head_of_year", "Head of Year"),
                    ("head_of_department", "Head of Department"),
                    ("class_teacher", "Class Teacher"),
                    ("nurse", "Nurse"),
                    ("admissions", "Admissions Officer"),
                    ("secretary", "Secretary"),
                    ("bursar", "Bursar"),
                ],
                max_length=30,
            ),
        ),
    ]
