# Generated by Django 6.0.8 on 2026-10-01 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gradebook", "0007_grade_ranges"),
        ("students", "0013_school_support_limits"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportConcern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Needs support"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Suggestion dismissed"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("auto", "Suggested by HouseMaster"),
                            ("manual", "Marked by staff"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "reasons",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"code": "low_average", "label": "..."}]',
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Why, in the teacher's words. Parents see it.",
                    ),
                ),
                (
                    "support_plan",
                    models.TextField(
                        blank=True,
                        help_text="What the school will do, and how parents can help.",
                    ),
                ),
                (
                    "review_date",
                    models.DateField(
                        blank=True,
                        help_text="When to check progress. Staff only.",
                        null=True,
                    ),
                ),
                ("created_by_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_by_name", models.CharField(blank=True, max_length=255)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("closing_note", models.TextField(blank=True)),
                ("parents_notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_concerns",
                        to="students.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_concerns",
                        to="students.student",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_concerns",
                        to="gradebook.term",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "open")),
                        fields=("student",),
                        name="one_open_support_concern_per_student",
                    )
                ],
            },
        ),
    ]
