# Generated by Django 6.0.8 on 2026-10-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportconcern",
            name="measures",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
