# Generated by Django 6.0.8 on 2026-10-08 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0017_ranking_min_share"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DisciplineIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("late", "Late"),
                            ("homework", "Homework not done"),
                            ("disruption", "Disrupting lessons"),
                            ("uniform", "Uniform"),
                            ("phone", "Phone or device"),
                            ("disrespect", "Disrespect"),
                            ("dishonesty", "Cheating or dishonesty"),
                            ("truancy", "Skipping lessons"),
                            ("bullying", "Bullying"),
                            ("fighting", "Fighting"),
                            ("damage", "Damage to property"),
                            ("substances", "Alcohol, drugs or smoking"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("minor", "Minor"),
                            ("moderate", "Moderate"),
                            ("serious", "Serious"),
                        ],
                        default="minor",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="What happened. Parents see it if the record is shared."
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("none", "No action yet"),
                            ("warning", "Warning"),
                            ("detention", "Detention"),
                            ("community", "Community work"),
                            ("meeting", "Meeting with parents"),
                            ("suspension", "Suspension"),
                            ("exclusion", "Exclusion"),
                            ("other", "Other"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "action_detail",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Detention Friday 3pm".',
                        max_length=300,
                    ),
                ),
                (
                    "staff_notes",
                    models.TextField(
                        blank=True, help_text="Staff only; never shown to parents."
                    ),
                ),
                ("shared_with_parents", models.BooleanField(default=False)),
                ("parents_notified_at", models.DateTimeField(blank=True, null=True)),
                ("recorded_by_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discipline_incidents",
                        to="students.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discipline_incidents",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["school", "-date"],
                        name="discipline__school__17c16c_idx",
                    )
                ],
            },
        ),
    ]
