# Generated by Django 6.0.8 on 2026-10-08 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discipline", "0001_initial"),
        ("students", "0017_ranking_min_share"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Merit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("work", "Excellent work"),
                            ("effort", "Effort"),
                            ("improvement", "Big improvement"),
                            ("kindness", "Kindness and respect"),
                            ("helping", "Helping others"),
                            ("leadership", "Leadership"),
                            ("service", "Service to the school"),
                            ("sport", "Sport"),
                            ("arts", "Music, drama or art"),
                            ("attendance", "Attendance and punctuality"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("points", models.PositiveSmallIntegerField(default=1)),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="What it was for. Parents see it if shared.",
                        max_length=500,
                    ),
                ),
                ("shared_with_parents", models.BooleanField(default=True)),
                ("awarded_by_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "awarded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merits",
                        to="students.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merits",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["school", "-date"],
                        name="discipline__school__40fa6f_idx",
                    )
                ],
            },
        ),
    ]
