# Generated by Django 6.0.7 on 2026-08-02 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gradebook', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_summary', models.TextField(help_text='AI-generated summary of trends across terms, strengths, and areas to watch.')),
                ('report_comment', models.TextField(help_text="AI-generated draft report comment, in the school's configured tone. Editable by teacher.")),
                ('tone_used', models.CharField(blank=True, help_text='The School.report_tone value in effect when this was generated.', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed / edited by teacher'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='gradebook.term')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'term'], name='reporting_s_student_50144e_idx')],
                'unique_together': {('student', 'term')},
            },
        ),
    ]
