# Generated by Django 6.0.8 on 2026-09-26 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def reviewed_to_submitted(apps, schema_editor):
    # "Reviewed" used to mean the teacher was done with it, which is what
    # "submitted for approval" means now.
    apps.get_model("reporting", "StudentReport").objects.filter(status="reviewed").update(status="submitted")


def submitted_to_reviewed(apps, schema_editor):
    apps.get_model("reporting", "StudentReport").objects.filter(status="submitted").update(status="reviewed")


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentreport",
            name="finalized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentreport",
            name="finalized_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="finalized_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentreport",
            name="review_note",
            field=models.TextField(
                blank=True,
                help_text="An admin's note on what to change, set when a report is sent back.",
            ),
        ),
        migrations.AddField(
            model_name="studentreport",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentreport",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="studentreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted for approval"),
                    ("finalized", "Finalized"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.RunPython(reviewed_to_submitted, submitted_to_reviewed),
    ]
