# Generated by Django 6.0.8 on 2026-09-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0002_report_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentreport",
            name="extra",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-system ratings for the report card: CBC competencies and values, IB approaches to learning.",
            ),
        ),
        migrations.AddField(
            model_name="studentreport",
            name="principal_comment",
            field=models.TextField(
                blank=True,
                help_text="The head's remarks, printed on report cards that have them (e.g. 8-4-4). Admins only.",
            ),
        ),
    ]
