# Generated by Django 6.0.8 on 2026-10-01 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0003_system_reporting"),
        ("students", "0013_school_support_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentreport",
            name="class_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="studentreport",
            name="education_system",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="studentreport",
            name="grading_scale",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="studentreport",
            name="school_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="students.schoolclass",
            ),
        ),
    ]
