# Generated by Django 6.0.8 on 2026-10-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0004_report_class_at_the_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentreport",
            name="class_recorded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
