# Generated by Django 6.0.8 on 2026-09-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guardians", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardian",
            name="address",
            field=models.TextField(blank=True, verbose_name="home address"),
        ),
        migrations.AddField(
            model_name="guardian",
            name="admin_note",
            field=models.TextField(
                blank=True, help_text="Private to the school's admins."
            ),
        ),
        migrations.AddField(
            model_name="guardian",
            name="occupation",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="guardian",
            name="phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="guardian",
            name="phone_alt",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="second phone"
            ),
        ),
        migrations.AddField(
            model_name="guardian",
            name="preferred_contact",
            field=models.CharField(
                blank=True,
                choices=[
                    ("call", "Phone call"),
                    ("sms", "SMS"),
                    ("whatsapp", "WhatsApp"),
                    ("email", "Email"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="guardian",
            name="relationship",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mother", "Mother"),
                    ("father", "Father"),
                    ("guardian", "Guardian"),
                    ("grandparent", "Grandparent"),
                    ("sibling", "Sibling"),
                    ("other", "Other relative"),
                ],
                max_length=20,
            ),
        ),
    ]
