# Generated by Django 6.0.8 on 2026-09-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guardians", "0002_contact_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardian",
            name="email_notifications",
            field=models.BooleanField(
                default=True,
                help_text="Email this parent when an announcement or report is published for them.",
            ),
        ),
    ]
