# Generated by Django 6.0.8 on 2026-09-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guardians", "0003_email_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardian",
            name="privacy_accepted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When they accepted the privacy notice while setting up their account.",
                null=True,
            ),
        ),
    ]
