# Generated by Django 6.0.8 on 2026-09-27 15:31

import django.db.models.deletion
import guardians.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guardians", "0004_privacy"),
        ("students", "0010_checklist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="guardianinvite",
            name="phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="guardianinvite",
            name="relationship",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mother", "Mother"),
                    ("father", "Father"),
                    ("guardian", "Guardian"),
                    ("grandparent", "Grandparent"),
                    ("sibling", "Sibling"),
                    ("other", "Other relative"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ClassSignupLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=guardians.models._generate_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signup_links_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signup_links",
                        to="students.school",
                    ),
                ),
                (
                    "school_class",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signup_link",
                        to="students.schoolclass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParentSignupRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "relationship",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mother", "Mother"),
                            ("father", "Father"),
                            ("guardian", "Guardian"),
                            ("grandparent", "Grandparent"),
                            ("sibling", "Sibling"),
                            ("other", "Other relative"),
                        ],
                        max_length=20,
                    ),
                ),
                ("admission_number", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting"),
                            ("approved", "Approved"),
                            ("rejected", "Turned down"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signup_requests_decided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signup_requests",
                        to="students.school",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signup_requests",
                        to="students.schoolclass",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signup_requests",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
