# Generated by Django 6.0.8 on 2026-10-09 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0017_ranking_min_share"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AbsenceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alerts_enabled", models.BooleanField(default=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absence_settings",
                        to="students.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AbsenceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("parents", models.PositiveSmallIntegerField(default=0)),
                ("corrected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absence_alerts",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "date"), name="one_absence_alert_a_day"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AbsenceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("illness", "Ill"),
                            ("appointment", "Medical or dental appointment"),
                            ("family", "Family reasons"),
                            ("religious", "Religious observance"),
                            ("travel", "Travel"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.CharField(blank=True, max_length=500)),
                ("reported_by_name", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("seen_by_name", models.CharField(blank=True, max_length=150)),
                ("seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absence_reports",
                        to="students.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absence_reports",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["school", "start_date", "end_date"],
                        name="absences_ab_school__9fc040_idx",
                    )
                ],
            },
        ),
    ]
