# Generated by Django 6.0.8 on 2026-09-26 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="kind",
            field=models.CharField(
                choices=[
                    ("direct", "Direct message"),
                    ("class_notice", "Class notice"),
                    ("class_group", "Class discussion"),
                ],
                default="direct",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="school_class",
            field=models.ForeignKey(
                blank=True,
                help_text="For class notices and discussions: the class whose parents are in it.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="students.schoolclass",
            ),
        ),
    ]
