# Generated by Django 6.0.8 on 2026-10-08 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gradebook", "0007_grade_ranges"),
        ("students", "0017_ranking_min_share"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("instructions", models.TextField(blank=True)),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Optional: a worksheet, video or page to use.",
                        max_length=500,
                    ),
                ),
                ("set_on", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "out_of",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Blank when it isn't marked out of a number.",
                        null=True,
                    ),
                ),
                ("set_by_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework",
                        to="students.school",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework",
                        to="students.schoolclass",
                    ),
                ),
                (
                    "set_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework",
                        to="gradebook.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["-due_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="HomeworkRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("handed_in", "Handed in"),
                            ("late", "Handed in late"),
                            ("missing", "Missing"),
                            ("excused", "Excused"),
                        ],
                        help_text="Blank until the teacher records it.",
                        max_length=12,
                    ),
                ),
                (
                    "mark",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        help_text="The teacher's feedback; the student and parents see it.",
                        max_length=1000,
                    ),
                ),
                (
                    "done_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the student marked it done.",
                        null=True,
                    ),
                ),
                (
                    "answer",
                    models.TextField(
                        blank=True, help_text="The student's typed answer or a link."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="homework.assignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework_records",
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["school_class", "due_date"],
                name="homework_as_school__1be70d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="homeworkrecord",
            constraint=models.UniqueConstraint(
                fields=("assignment", "student"), name="unique_homework_record"
            ),
        ),
    ]
