# Generated by Django 6.0.8 on 2026-09-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="term",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="term",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
