# Generated by Django 6.0.8 on 2026-09-27 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0002_term_locking"),
        ("students", "0006_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="credits",
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.CreateModel(
            name="SubjectReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "effort",
                    models.CharField(
                        blank=True,
                        help_text="British schools: effort grade, 1 (excellent) to 4.",
                        max_length=10,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        blank=True,
                        help_text="British schools: target grade, e.g. A or 7.",
                        max_length=10,
                    ),
                ),
                (
                    "criteria",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='IB MYP: {"A": 0-8, "B": 0-8, "C": 0-8, "D": 0-8}.',
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_reports",
                        to="students.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_reports",
                        to="gradebook.subject",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_reports",
                        to="gradebook.term",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "subject", "term")},
            },
        ),
    ]
