# Generated by Django 6.0.8 on 2026-09-27 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0003_system_reporting"),
        ("students", "0006_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Its share of the term result, e.g. 30.",
                        max_digits=5,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_types",
                        to="students.school",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("school", "name")},
            },
        ),
        migrations.AddField(
            model_name="grade",
            name="assessment_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Which kind of assessment this mark is from; decides its weight.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grades",
                to="gradebook.assessmenttype",
            ),
        ),
    ]
