# Generated by Django 6.0.8 on 2026-09-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0005_subject_choices"),
        ("students", "0011_setup_stages"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="subject",
            name="education_system",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("school", "name", "education_system")},
        ),
    ]
