# Generated by Django 6.0.8 on 2026-09-28 11:00

from django.db import migrations, models
from django.db.models import F, Q

MAX_IDS_SHOWN = 50


def refuse_out_of_range_grades(apps, schema_editor):
    """
    Stop before adding the constraints if existing grades break them, so the
    deploy fails cleanly instead of half-way through. Only row IDs are
    printed, never names or marks. See docs/HUMAN_ACTIONS.md (H-6).
    """
    Grade = apps.get_model("gradebook", "Grade")
    bad = list(
        Grade.objects.filter(Q(max_score__lte=0) | Q(score__lt=0) | Q(score__gt=F("max_score")))
        .order_by("pk").values_list("pk", flat=True)
    )
    if bad:
        shown = ", ".join(str(pk) for pk in bad[:MAX_IDS_SHOWN])
        more = f" and {len(bad) - MAX_IDS_SHOWN} more" if len(bad) > MAX_IDS_SHOWN else ""
        raise RuntimeError(
            f"{len(bad)} grade(s) have a mark below 0, above the maximum, or a maximum of 0 or less "
            f"(IDs {shown}{more}). Correct them, then deploy again. "
            "scripts/preflight_range_checks.sql lists them the same way."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0006_subject_sections"),
        ("students", "0011_setup_stages"),
    ]

    operations = [
        migrations.RunPython(refuse_out_of_range_grades, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_score__gt", 0)),
                name="grade_max_score_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.CheckConstraint(
                condition=models.Q(("score__gte", 0)), name="grade_score_not_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.CheckConstraint(
                condition=models.Q(("score__lte", models.F("max_score"))),
                name="grade_score_within_max",
            ),
        ),
    ]
