# Generated by Django 6.0.8 on 2026-09-26 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_name", models.CharField(blank=True, max_length=255)),
                (
                    "action",
                    models.CharField(
                        help_text='e.g. "grade.updated", "staff.deactivated"',
                        max_length=60,
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        help_text="Plain-English description of what happened.",
                        max_length=500,
                    ),
                ),
                ("target_type", models.CharField(blank=True, max_length=60)),
                ("target_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="students.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["school", "-created_at"],
                        name="activity_ac_school__493d8d_idx",
                    )
                ],
            },
        ),
    ]
