# Generated by Django 6.0.8 on 2026-10-08 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0017_ranking_min_share"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("sport", "Sport"),
                            ("music", "Music"),
                            ("arts", "Drama and art"),
                            ("academic", "Academic"),
                            ("service", "Service and volunteering"),
                            ("club", "Club or society"),
                            ("other", "Other"),
                        ],
                        default="club",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "meets",
                    models.CharField(
                        blank=True,
                        help_text='When it meets, e.g. "Tuesdays 3:30pm".',
                        max_length=120,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "leaders",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The staff who run it: they manage members, registers and fixtures.",
                        related_name="led_clubs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clubs",
                        to="students.school",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ClubMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Captain". Blank for a member.',
                        max_length=60,
                    ),
                ),
                ("joined_on", models.DateField()),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="clubs.club",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_memberships",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["student__last_name", "student__first_name"],
            },
        ),
        migrations.CreateModel(
            name="ClubSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "note",
                    models.CharField(
                        blank=True, help_text="Staff only.", max_length=300
                    ),
                ),
                ("taken_by_name", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="clubs.club",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ClubAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("excused", "Excused"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_attendance",
                        to="students.student",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks",
                        to="clubs.clubsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fixture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                (
                    "opponent",
                    models.CharField(
                        help_text="Who they play, or the event's name.", max_length=120
                    ),
                ),
                (
                    "venue",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("away", "Away"),
                            ("neutral", "Neutral venue"),
                        ],
                        default="home",
                        max_length=10,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "competition",
                    models.CharField(
                        blank=True, help_text='e.g. "County league".', max_length=120
                    ),
                ),
                (
                    "team",
                    models.CharField(
                        blank=True, help_text='e.g. "Under 15 A".', max_length=60
                    ),
                ),
                ("our_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "their_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "result_note",
                    models.CharField(
                        blank=True,
                        help_text='The result in words, e.g. "Won on penalties" or "2nd of 8".',
                        max_length=300,
                    ),
                ),
                (
                    "report",
                    models.TextField(
                        blank=True,
                        help_text="A short report. Parents of the squad see it.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fixtures",
                        to="clubs.club",
                    ),
                ),
                (
                    "players",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The squad: parents see that their child was picked.",
                        related_name="fixtures",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="club",
            constraint=models.UniqueConstraint(
                fields=("school", "name"), name="unique_club_name_per_school"
            ),
        ),
        migrations.AddConstraint(
            model_name="clubmember",
            constraint=models.UniqueConstraint(
                fields=("club", "student"), name="unique_club_member"
            ),
        ),
        migrations.AddConstraint(
            model_name="clubsession",
            constraint=models.UniqueConstraint(
                fields=("club", "date"), name="unique_club_session_per_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="clubattendance",
            constraint=models.UniqueConstraint(
                fields=("session", "student"), name="unique_club_attendance_mark"
            ),
        ),
        migrations.AddIndex(
            model_name="fixture",
            index=models.Index(
                fields=["club", "date"], name="clubs_fixtu_club_id_e87ba3_idx"
            ),
        ),
    ]
