# Generated by Django 6.0.8 on 2026-10-08 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_staff_roles"),
        ("students", "0017_ranking_min_share"),
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoverAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Work set on the class page".',
                        max_length=200,
                    ),
                ),
                ("assigned_by_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cover_teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cover_lessons",
                        to="accounts.profile",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cover",
                        to="timetable.lesson",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cover_assignments",
                        to="students.school",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "lesson__period__start_time"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lesson", "date"), name="one_cover_per_lesson_per_day"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StaffAbsence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("sick", "Sick"),
                            ("training", "Training or course"),
                            ("trip", "School trip"),
                            ("personal", "Personal or family"),
                            ("other", "Other"),
                        ],
                        default="sick",
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("recorded_by_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "periods",
                    models.ManyToManyField(
                        blank=True, related_name="absences", to="timetable.period"
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_absences",
                        to="students.school",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["school", "start_date", "end_date"],
                        name="timetable_s_school__8a425f_idx",
                    )
                ],
            },
        ),
    ]
